AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ParamCrawlerS3BucketName:
    Type: String
    Description: "Name of the S3 bucket"

  ParamCrawlerTriggerLambdaArn:
    Type: String
    Description: "ARN of the Lambda function that triggers the Glue Crawler"

Resources:

  svcCrawlerEventBridgeRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "events.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "StartGlueCrawlerPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "glue:StartCrawler"
                Resource: !Sub "arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:crawler/${ParamCrawlerS3BucketName}-crawler"

  CrawlerEventRule:
    Type: "AWS::Events::Rule"
    Properties:
      Name: !Sub "${ParamCrawlerS3BucketName}-s3-event-rule"
      EventPattern:
        source:
          - "aws.s3"
        detail-type:
          - "Object Created"
        detail:
          bucket:
            name:
              - !Ref ParamCrawlerS3BucketName
      Targets:
        - Arn: !Ref ParamCrawlerTriggerLambdaArn
          Id: "LambdaCrawlerTarget"

  LambdaInvokePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref ParamCrawlerTriggerLambdaArn
      Principal: "events.amazonaws.com"
