AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ParamCrawlerS3BucketName:
    Type: String
    Description: "Name of the S3 bucket"

  ParamCrawlerS3KMSKey:
    Type: String
    Description: "KMS Key used to encrypt the S3 bucket"

Resources:
  svcGlueCrawlerRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      RoleName: !Sub 'svc-Crawler-${AWS::Region}'
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: 'Allow'
            Principal: 
              Service: 
                - 'glue.amazonaws.com'
            Action: 
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: 'GlueCrawlerPolicy'
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: 'Allow'
                Action: 
                  - 's3:GetObject'
                  - 's3:ListBucket'
                Resource: 
                  - !Sub 'arn:${AWS::Partition}:s3:::${ParamCrawlerS3BucketName}'
                  - !Sub 'arn:${AWS::Partition}:s3:::${ParamCrawlerS3BucketName}/*'
              - Effect: 'Allow'
                Action: 
                  - 'kms:Decrypt'
                  - 'kms:DescribeKey'
                Resource: !Ref ParamCrawlerS3KMSKey
              
  CrawlerGlueDatabase:
    Type: 'AWS::Glue::Database'
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub '${ParamCrawlerS3BucketName}_db'

  Crawler:
    Type: 'AWS::Glue::Crawler'
    Properties:
      Name: !Sub '${ParamCrawlerS3BucketName}-crawler' 
      Role: !Ref svcGlueCrawlerRole
      DatabaseName: !Ref CrawlerGlueDatabase     
      Targets:
        S3Targets:
          - Path: !Sub 's3://${ParamCrawlerS3BucketName}/'
      TablePrefix: ""
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "DEPRECATE_IN_DATABASE"
      RecrawlPolicy:
        RecrawlBehavior: "CRAWL_EVENT_MODE" # Recrawls only changed objects