AWSTemplateFormatVersion: '2010-09-09'
Description: "Master stack that ensures correct order of S3 and EC2"

Parameters:
  BucketName:
    Type: String
    Description: 'Name of the S3 Bucket'
    AllowedPattern: '^[a-z0-9-]{5,40}$'

Resources:
  S3BucketStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: "https://cf-templates-795524854110-ap-south-1.s3.amazonaws.com/glue-crawler/s3kms.yaml"
      Parameters:
        BucketName: !Ref BucketName  # Pass BucketName parameter to the nested stack

  GlueCrawlerStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: "https://cf-templates-795524854110-ap-south-1.s3.amazonaws.com/glue-crawler/gluecrawler.yaml"
      Parameters:
        NationS3BucketName: !ImportValue NationS3BucketName