AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  ParamCrawlerS3BucketName:
    Type: String
    Description: 'Name of the S3 Bucket'
    AllowedPattern: '^[a-z0-9-]{5,40}$'

Resources:

  CrawlerS3KMSKey:
    Type: 'AWS::KMS::Key'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      KeyUsage: ENCRYPT_DECRYPT
      Origin: AWS_KMS
      KeySpec: SYMMETRIC_DEFAULT
      MultiRegion: false
      BypassPolicyLockoutSafetyCheck: false
      RotationPeriodInDays: 90
      KeyPolicy:
        Version: "2012-10-17"
        Id: "CloudTrailS3KMSPolicy"
        Statement:
          # Allow CloudTrail to use the KMS key for encryption/decryption
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action:
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKey"
            Resource: "*"

          # Allow S3 bucket to use the KMS key for encryption/decryption
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKey"
            Resource: "*"
            Condition:
              StringEquals:
                "aws:SourceArn": !Sub "arn:${AWS::Partition}:s3:::${ParamCrawlerS3BucketName}-${AWS::Region}-${AWS::AccountId}"

  CrawlerS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: !Sub '${ParamCrawlerS3BucketName}-${AWS::Region}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref CrawlerS3KMSKey
      VersioningConfiguration:
        Status: Enabled
      NotificationConfiguration:
        EventBridgeConfiguration:  # <-- Enables EventBridge notifications
          EventBridgeEnabled: true

  CrawlerS3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref CrawlerS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 
              - s3:GetBucketAcl
            Resource: !Sub "arn:${AWS::Partition}:s3:::${ParamCrawlerS3BucketName}-${AWS::Region}-${AWS::AccountId}"
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 
              - s3:PutObject
            Resource: !Sub "arn:${AWS::Partition}:s3:::${ParamCrawlerS3BucketName}-${AWS::Region}-${AWS::AccountId}/AWSLogs/${AWS::AccountId}/*"
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 
              - s3:ListBucket
            Resource: !Sub "arn:${AWS::Partition}:s3:::${ParamCrawlerS3BucketName}-${AWS::Region}-${AWS::AccountId}"

  CrawlerS3BucketTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      S3BucketName: !Ref CrawlerS3Bucket
      IsMultiRegionTrail: false
      IsLogging: true
      IncludeGlobalServiceEvents: true
      EnableLogFileValidation: true
      EventSelectors:
        - ReadWriteType: WriteOnly
          DataResources:
               - Type: AWS::S3::Object
                 Values:
                 - !Sub "arn:${AWS::Partition}:s3:::${ParamCrawlerS3BucketName}-${AWS::Region}-${AWS::AccountId}/*"

      KMSKeyId: !GetAtt CrawlerS3KMSKey.Arn  

Outputs:

  CrawlerS3BucketName:
    Description: 'Name of the S3 Bucket'
    Value: !Ref CrawlerS3Bucket
    Export:
      Name: CrawlerS3BucketName

  CrawlerS3KMSKeyArn:
    Description: 'KMS Key for the Crawler S3 Bucket'
    Value: !GetAtt CrawlerS3KMSKey.Arn
    Export:
      Name: CrawlerS3KMSKeyArn

  CrawlerS3BucketTrailArn:
    Description: 'CloudTrail ARN for the Crawler S3 Bucket'
    Value: !GetAtt CrawlerS3BucketTrail.Arn
    Export:
      Name: CrawlerS3BucketTrailArn