AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  ParamCrawlerS3BucketName:
    Type: String
    Description: 'Name of the S3 Bucket'
    AllowedPattern: '^[a-z0-9-]{5,40}$'

Resources:

  CrawlerS3KMSKey:
    Type: 'AWS::KMS::Key'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete 
    Properties:
      KeyUsage: ENCRYPT_DECRYPT
      Origin: AWS_KMS
      KeySpec: SYMMETRIC_DEFAULT
      MultiRegion: false
      BypassPolicyLockoutSafetyCheck: false
      RotationPeriodInDays: 90

  CrawlerS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: !Sub '${ParamCrawlerS3BucketName}-${AWS::Region}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref CrawlerS3KMSKey
      VersioningConfiguration:
        Status: Enabled
      NotificationConfiguration:
           QueueConfigurations:
                - Event: 's3:ObjectCreated:*'
                  Queue: !GetAtt [CrawlerS3BucketEventQueue, Arn]

  CrawlerS3BucketEventQueue:
    Type: 'AWS::SQS::Queue'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      MessageRetentionPeriod: 86400
      QueueName: !Sub 's3-event-queue-${ParamCrawlerS3BucketName}-${AWS::Region}-${AWS::AccountId}'

  CrawlerS3QueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      Queues:
        - !Ref CrawlerS3BucketEventQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "s3.amazonaws.com"
            Action: "sqs:SendMessage"
            Resource: !GetAtt CrawlerS3BucketEventQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !GetAtt CrawlerS3Bucket.Arn

Outputs:

  CrawlerS3BucketName:
    Description: 'Name of the Crawler S3 Bucket'
    Value: !Ref CrawlerS3Bucket
    Export:
      Name: CrawlerS3BucketName

  CrawlerS3KMSKey:
    Description: 'KMS Key for the Crawler S3 Bucket'
    Value: !GetAtt CrawlerS3KMSKey.Arn
    Export:
      Name: CrawlerS3KMSKey

  CrawlerS3BucketEventQueue:
    Description: 'Event Queue for the Crawler S3 Bucket'
    Value: !Ref CrawlerS3BucketEventQueue
    Export:
      Name: CrawlerS3BucketEventQueue