AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  ParamCrawlerS3BucketName:
    Type: String
    Description: 'Name of the S3 Bucket'
    AllowedPattern: '^[a-z0-9-]{5,40}$'

Resources:

  CrawlerS3KMSKey:
    Type: 'AWS::KMS::Key'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete 
    Properties:
      KeyUsage: ENCRYPT_DECRYPT
      Origin: AWS_KMS
      KeySpec: SYMMETRIC_DEFAULT
      MultiRegion: false
      BypassPolicyLockoutSafetyCheck: false
      RotationPeriodInDays: 90

  CrawlerS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: !Sub '${ParamCrawlerS3BucketName}-${AWS::Region}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref CrawlerS3KMSKey
      VersioningConfiguration:
        Status: Enabled
      NotificationConfiguration:
        EventBridgeConfiguration:  # <-- Enables EventBridge notifications
          EventBridgeEnabled: true

Outputs:

  CrawlerS3BucketName:
    Description: 'Name of the S3 Bucket'
    Value: !Ref CrawlerS3Bucket
    Export:
      Name: CrawlerS3BucketName

  CrawlerS3KMSKeyArn:
    Description: 'KMS Key for the Crawler S3 Bucket'
    Value: !GetAtt CrawlerS3KMSKey.Arn
    Export:
      Name: CrawlerS3KMSKeyArn