AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ParamCrawlerS3BucketName:
    Type: String
    Description: Name of the S3 Bucket
    AllowedPattern: ^[a-z0-9-]{5,40}$

  ParamCrawlerTriggerLambdaArn:
    Type: String
    Description: ARN of the Lambda that is invoked from S3 events

Resources:

  CrawlerS3KMSKey:
    Type: AWS::KMS::Key
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      KeyUsage: ENCRYPT_DECRYPT
      Origin: AWS_KMS
      KeySpec: SYMMETRIC_DEFAULT
      MultiRegion: false
      BypassPolicyLockoutSafetyCheck: false
      RotationPeriodInDays: 90
      KeyPolicy:
        Version: '2012-10-17'
        Id: CloudTrailS3KMSPolicy
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'

          - Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:user/general-admin
            Action: kms:*
            Resource: '*'

          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: !Sub arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${AWS::StackName}-CrawlerS3KMSKey
            Condition:
              StringEquals:
                aws:SourceArn: !Sub arn:${AWS::Partition}:s3:::${ParamCrawlerS3BucketName}-${AWS::Region}-${AWS::AccountId}
  
  CrawlerS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: !Sub ${ParamCrawlerS3BucketName}-${AWS::Region}-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref CrawlerS3KMSKey
      VersioningConfiguration:
        Status: Enabled
      NotificationConfiguration:
        LambdaConfigurations:
             - Event: S3:ObjectCreated:*
               Function: !Ref ParamCrawlerTriggerLambdaArn
  
  CrawlerTrailS3KMSKey:
    Type: AWS::KMS::Key
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      KeyUsage: ENCRYPT_DECRYPT
      Origin: AWS_KMS
      KeySpec: SYMMETRIC_DEFAULT
      MultiRegion: false
      BypassPolicyLockoutSafetyCheck: false
      EnableKeyRotation: true
      RotationPeriodInDays: 90
      KeyPolicy:
        Version: '2012-10-17'
        Id: CloudTrailS3KMSPolicy
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'

          - Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:user/general-admin
            Action: kms:*
            Resource: '*'

          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: !Sub arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${AWS::StackName}-CrawlerTrailS3KMSKey

          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: !Sub arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${AWS::StackName}-CrawlerTrailS3KMSKey
            Condition:
              StringEquals:
                aws:SourceArn: !Sub arn:${AWS::Partition}:s3:::${ParamCrawlerS3BucketName}-trail-${AWS::Region}-${AWS::AccountId}
  
  CrawlerTrailS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: !Sub ${ParamCrawlerS3BucketName}-trail-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref CrawlerTrailS3KMSKey
      VersioningConfiguration:
        Status: Enabled

Outputs:
  
  CrawlerS3BucketName:
    Description: Name of the S3 Bucket
    Value: !Ref CrawlerS3Bucket
    Export:
      Name: CrawlerS3BucketName
  
  CrawlerS3KMSKeyArn:
    Description: KMS Key for the Crawler S3 Bucket
    Value: !GetAtt CrawlerS3KMSKey.Arn
    Export:
      Name: CrawlerS3KMSKeyArn